### ISSUE TITLE
Consul-agent lookups other members on 127.0.0.1:53: no such host

### ISSUE THREAD

**Issue by EdwardStudy** [cloudfoundry-incubator/consul-release#77] opened 2017-09-18 14:23 UTC
I used [cf-deployment](https://github.com/cloudfoundry/cf-deployment) to deploy cf. And Updating consul VM occur error after created VMs.

And information is below in`/var/vcap/sys/log/consul_agent/consul_agent.stdout.log`:
```
{"timestamp":"1505739599.973006248","source":"confab","message":"confab.agent-client.join-members.consul-api-agent.join","log_level":1,"data":{"member":"ed8f4bc8-75c5-4c92-b58e-8d6f575220b6.consul.default.automation-cf.bosh"}}
    2017/09/18 12:59:59 [INFO] agent: (LAN) joining: [ed8f4bc8-75c5-4c92-b58e-8d6f575220b6.consul.default.automation-cf.bosh]
    2017/09/18 13:00:02 [ERR] dns: recurse failed: read tcp 10.165.227.23:57920->10.165.227.47:53: i/o timeout
    2017/09/18 13:00:03 [WARN] memberlist: Failed to resolve ed8f4bc8-75c5-4c92-b58e-8d6f575220b6.consul.default.automation-cf.bosh: lookup ed8f4bc8-75c5-4c92-b58e-8d6f575220b6.consul.default.automation-cf.bosh on 127.0.0.1:53: no such host
    2017/09/18 13:00:03 [INFO] agent: (LAN) joined: 0 Err: 1 error(s) occurred:

* Failed to resolve ed8f4bc8-75c5-4c92-b58e-8d6f575220b6.consul.default.automation-cf.bosh: lookup ed8f4bc8-75c5-4c92-b58e-8d6f575220b6.consul.default.automation-cf.bosh on 127.0.0.1:53: no such host
    2017/09/18 13:00:03 [ERR] http: Request PUT /v1/agent/join/ed8f4bc8-75c5-4c92-b58e-8d6f575220b6.consul.default.automation-cf.bosh, error: 1 error(s) occurred:

* Failed to resolve ed8f4bc8-75c5-4c92-b58e-8d6f575220b6.consul.default.automation-cf.bosh: lookup ed8f4bc8-75c5-4c92-b58e-8d6f575220b6.consul.default.automation-cf.bosh on 127.0.0.1:53: no such host from=127.0.0.1:47926
```
`ed8f4bc8-75c5-4c92-b58e-8d6f575220b6.consul.default.automation-cf.bosh` is another consul node.
And I could dig others members.

and `/etc/resolv.conf` file contains:
```
nameserver 127.0.0.1
nameserver 10.165.227.47
nameserver 8.8.8.8
nameserver 10.0.80.11
```

**Comment by evanfarrar** [comment] 2017-09-18 18:26
Hey @EdwardStudy I am not too familiar with that error message, Consul usually finds itself on the URL "cf.internal", do you have any special ops files enabled with your deploy?

@cppforlife does this look familiar to you? It doesn't look too familiar to me.

**Comment by EdwardStudy** [comment] 2017-09-19 00:50
@evanfarrar Well. I checked my `interpolate` command. `stemcell.yml` was directing to the specific version of stemcell. `rename-deployment.yml`  only renamed deployment name.

```
CF_PREFIX=bosh-cf-component-ed
CF_DOMAIN=softlayer.com
DEPLOYMENT_NAME=automation-cf
bosh2 int cf-deployment/cf-deployment.yml \
  --vars-store env-repo/deployment-vars.yml \
  -o stemcell.yml \
  -o cf-deployment/operations/rename-deployment.yml \
  -v deployment_name=${DEPLOYMENT_NAME} \
  -v system_domain=${CF_PREFIX}.${CF_DOMAIN} \
  > ${deployment_dir}/cf.yml

bosh2 -d ${DEPLOYMENT_NAME} -n deploy ${deployment_dir}/cf.yml
```

**Comment by evanfarrar** [comment] 2017-09-19 16:11
Ok, that explains where "automation-cf" came from, we might be able to reproduce the issue now

**Comment by EdwardStudy** [comment] 2017-09-19 16:16
Sorry, I corrected my words below. digging others consul could not get any answer. And ping also failed.

```
ping ed8f4bc8-75c5-4c92-b58e-8d6f575220b6.consul.default.automation-cf.bosh
ping: unknown host ed8f4bc8-75c5-4c92-b58e-8d6f575220b6.consul.default.automation-cf.bosh
dig ed8f4bc8-75c5-4c92-b58e-8d6f575220b6.consul.default.automation-cf.bosh

; <<>> DiG 9.9.5-3ubuntu0.14-Ubuntu <<>> ed8f4bc8-75c5-4c92-b58e-8d6f575220b6.consul.default.automation-cf.bosh
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 15058
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 2800
;; QUESTION SECTION:
;ed8f4bc8-75c5-4c92-b58e-8d6f575220b6.consul.default.automation-cf.bosh.    IN A

;; AUTHORITY SECTION:
bosh.            300    IN    SOA    localhost. hostmaster.localhost. 1505828247 10800 604800 30 3600

;; Query time: 94 msec
;; SERVER: 10.165.227.47#53(10.165.227.47)
;; WHEN: Tue Sep 19 14:00:48 UTC 2017
;; MSG SIZE  rcvd: 155
```

**Comment by rowanjacobs** [comment] 2017-09-27 00:00
This issue seems related to BOSH DNS, which comprises an agent in the stemcell and a DNS server on the director.

Which version of `bosh-deployment` and which stemcell version are you using?

**Comment by rowanjacobs** [comment] 2017-09-27 16:22
Also, can you try to replicate this with the latest `bosh-deployment` and newest stemcell?

**Comment by EdwardStudy** [comment] 2017-09-28 01:34
I think that I used PowerDNS not BOSH DNS. We maintained our [bosh-deployment](https://github.com/bluebosh/bosh-deployment/tree/new_softlayer_cpi) for new cpi dev. And stemcell version is 3445.2.

```
bosh2 int bosh-deployment/bosh.yml \
    -o bosh-deployment/powerdns.yml \
    -o bosh-deployment/softlayer/cpi-base.yml \
    -o bosh-deployment/softlayer/dynamic-director.yml \
    -o bosh-deployment/jumpbox-user.yml \
    -o ./remove-health-monitor.yml \
    -v internal_ip=$SL_VM_PREFIX.$SL_VM_DOMAIN \
    -v dns_recursor_ip=127.0.0.1 \
    -v director_name=bats-director \
    -v sl_director_fqn=$SL_VM_PREFIX.$SL_VM_DOMAIN \
    -v sl_datacenter=$SL_DATACENTER \
    -v sl_vlan_public=$SL_VLAN_PUBLIC \
    -v sl_vlan_private=$SL_VLAN_PRIVATE \
    -v sl_vm_name_prefix=$SL_VM_PREFIX \
    -v sl_vm_domain=$SL_VM_DOMAIN \
    -v sl_username=$SL_USERNAME \
    -v sl_api_key=$SL_API_KEY \
    --vars-store ${deployment_dir}/director-creds.yml \
    >${deployment_dir}/director.yml

bosh2 create-env \
    --state=${deployment_dir}/director-state.json \
    --vars-store ${deployment_dir}/director-creds.yml \
    ${deployment_dir}/director.yml
```
So what the relevance commits in `bosh-deployment` recently. Thank you~

**Comment by rowanjacobs** [comment] 2017-09-28 19:12
We don't know much about PowerDNS or test Consul against it. Additionally, your fork is 3 months behind master and there have been a lot of changes especially to DNS in the main bosh-deployment repo since the fork. Your stemcell is one version behind but I don't think that is the root cause of the issue.

**Comment by EdwardStudy** [comment] 2017-09-29 02:04
@rowanjacobs Thank you. I'll try the latest version of these kinds of stuff. And what is your recommendation of DNS, Bosh DNS or PowerDNS?

**Comment by mcwumbly** [comment] 2017-10-12 18:47
I think the world is moving toward BOSH DNS, but that question may be a good one to discuss in the #bosh channel on cloudfoundry slack.

Going to close this issue.

**Closed by mcwumbly** 2017-10-12 18:47 UTC
Labels: in progress
